config/routes.rb
Rails.application.routes.draw do

  
  root to: 'pages#home' 

  get '/welcome', to: 'pages#welcome'
  get '/team', to: 'pages#team'
  get '/contact', to: 'pages#contact'

  get "sign_up", to: "sessions#new"
  post "sign_up", to: "sessions#create"


  resources :posts
  resources :users
  resources :comments
  resources :sessions, only: [:new, :create, :destroy] 

  #resources :posts do
    #resources :comments
  #end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    #belongs_to :user
    #belongs_to :post
    
  
    #validates :content,
    #presence: {message:"Le contenu est obligatoire"},
    #length:   {minimum: 2, message:"Le commentaire doit faire minimum 2 caractères"}
    #validates :user_id, presence: true
    #validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    #belongs_to :user
    #has_many :comments, dependent: :destroy

    #validates :title,
    #presence: true
    
  
    #validates :title, 
      #presence: {message:"Le titre est obligatoire"}, 
      #length:   {minimum: 2,maximum: 30, message:"Le titre doit faire entre 2 et 30 caractères"}
      
    #validates :content,
      #presence: {message:"Le potin est obligatoire"},
      #length:   {minimum: 10, message:"Le potin doit faire minimum 10 caractères"}
  end

app/models/user.rb
class User < ApplicationRecord
    #has_many :posts, dependent: :destroy,
    #has_many :comments,
    has_secure_password
   
    #validates :email, uniqueness: true, 
    #presence: true, 
    #uniqueness: {case_sensitive: false },
    #format: {with: /\A[^@\s]+@[^@\s]+\z/},
    #validates :first_name, presence: true,
    #validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include SessionsHelper
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
  def index
    @comments = Comment.all
  end
    
  def new
    @comment = Comment.new
  end
    
  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.create(comment_params)
    redirect_to comments_path
  end
  
  # DELETE /posts/1
  def destroy
    @comment= Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
  end
  
    
  end

  #######
  private
  #######

  def comment_params
    params.require(:comment).permit(:content)
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

    def welcome
    end

    def team
    end

    def contact
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    #filtres pr les actions show/edit/update/destroy
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user, only: [:create, :update]

    # GET /posts
    def index
        @posts = Post.all
    end

    ## GET /posts/1 
    def show
    end

    ## GET /posts/1/edit
    def edit
    end

    # PATCH/PUT /posts/1
    def update
        @post.update(post_params)
        redirect_to posts_path
    end

    # GET /posts/new
    def new 
        @post = Post.new
        unless current_user
            flash[:danger] = "Please log in."
            redirect_to new_session_path
          else
    end
end

    # POST /posts
    def create
        @post = Post.create(post_params)
        #@post.user = User.find_by(id:session[:user_id])
        if @post.save
            flash[:success] = "Potin bien créé !"
        redirect_to posts_path
        else
        render "new"
        end
    end

    # DELETE /posts/1
    def destroy
        @post.destroy
        redirect_to posts_path
    end

#fin de ma classe
end


#######
private
#######

def set_post
    @post = Post.find(params[:id])
end

def post_params
    params.require(:post).permit(:title, :content)
end

def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController



  def create
    #render plain: "Thanks you buddy!"
    user = User.find_by(email:params[:email])
    if user && user.authenticate(params[:password])
    session[:user_id] = user.id  

    #@user = User.new(user_params)
    #if @user.save
    redirect_to root_path, notice: "Succefully created account"
    else
    flash.now[:danger] = 'Something was wrong'
    render :new
    end
  end

  def new
    @user = User.new
  end


  def destroy 
    session.delete(:user_id)
    redirect_to root_path
  end

end

private
 


#def user_params
  #params.require(:user).permit(email, :password, :password_confirmation)
#end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
    
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
    session[:user_id] = @user.id
    redirect_to users_path
    else
    render "new"
    end
  end

  # DELETE /posts/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
end


########
private
#######

def user_params
  params.require(:user).permit(:email, :password)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
    end

end

app/views/comments/index.html.erb
<h1>Comments :</h1>


<% @comments.each do |comment| %>
    <p>content : <%= comment.content %><p>
    <p>
    <a href="<%= comment_path(comment.id) %>" class="btn btn-primary">Show more</a>
    <a href="<%= comment_path(comment.id) %>" class="btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE">Delete</a>
    </p>
<% end %>

<p>
    <a href="<%= new_comment_path %>" class="btn btn-success">New comment</a> 
</p>

app/views/comments/new.html.erb
<h1>New comment :</h1>

<%= form_with model: @comment do |form| %>

    <div class="form-group">
    <label>Content :</label>
    <%= form.text_area :content, class: "form-control" %>
    </div>

    <div class="form-group" style="padding-top: 1rem;">
    <button type="submit" class="btn btn-primary">New comment</button>
    </div>
       
<% end %>

app/views/comments/show.html.erb
<h1><%= @comment.content %></h1>


<p>
    <a href="<%= comments_path %>" class="btn btn-primary">Back</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <!-- CDN BOOTSTRAP -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    
  </head>

    <body>

    
 <header>
      <div class="bg-dark collapse" id="navbarHeader" style="">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="#" class="text-white">Follow on Twitter</a></li>
                <li><a href="#" class="text-white">Like on Facebook</a></li>
                <li><a href="#" class="text-white">Email me</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Hot butt dog</strong>
          </a>
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header> 


    
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">The HALLOWEEN Gossip Project</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/welcome">Welcome homepage</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/team">Team</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contact">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= posts_path%>">Posts ton Gossip</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= users_path %>">Users</a>
        </li>
        <li class="nav-item">
         <a class="nav-link" href="<%= comments_path %>">Comment</a>
        </li>
          
      </ul>
      <form class="d-flex">
        <div class="d-flex justify-content-center">
        <a class="btn btn-outline-success" href="/users/new">Sign up</a>
        <p></p>
      </div>
      </form>
    </div>
  </div>
  <!-- Si pas connecter dropdown-->
  <%if session[:user_id] == nil%>
    <div class="dropdown">
      <button class="btn btn-outline-danger dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">Connexion</button>
      <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
        <li><a class="dropdown-item" href=<%= new_user_path %>>Sign up</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href=<%= new_session_path %>>Sign in</a></li>
      </ul>
    </div>
  <!-- sinon bouton déco-->
  <%else%>

    <div>

      <a href="<%= session_path(session.id) %>" class="btn btn-outline-danger" data-confirm="êtes-vous sur de vouloir vous déconnecter?" data-method="DELETE">Déconnexion</a>
          
    </div>
  <%end%>
</nav>

  <div class="container" style="padding-top: 2rem; margin-left: 1rem;">




  





 
  <%= yield %>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

  </body>
</html>

app/views/layouts/footer.html.erb
<div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
        <li class="nav-item dropup">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown10" data-bs-toggle="dropdown" aria-expanded="false">Dropup</a>
          <ul class="dropdown-menu" aria-labelledby="dropdown10">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>

    

app/views/pages/contact.html.erb
<div class="container contact-form">
  <div class="contact-image">
    <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact"/>
  </div>
  <form method="post">
  <h3>Drop Us a Message</h3>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <input type="text" name="txtName" class="form-control" placeholder="Your Name *" value="" />
      </div>
      <div class="form-group">
        <input type="text" name="txtEmail" class="form-control" placeholder="Your Email *" value="" />
      </div>
      <div class="form-group">
        <input type="text" name="txtPhone" class="form-control" placeholder="Your Phone Number *" value="" />
      </div>
        <div class="form-group">
          <input type="submit" name="btnSubmit" class="btnContact" value="Send Message" />
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <textarea name="txtMsg" class="form-control" placeholder="Your Message *" style="width: 100%; height: 150px;"></textarea>
        </div>
      </div>
    </div>
  </form>

<div class="container">
<div class="jumbotron">
  <h1 class="display-4">contact us!</h1>
  <p class="lead">information.</p>
  <hr class="my-4">
  <p>It uses utility .... </p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>
</div>


</div>

app/views/pages/team.html.erb
<div class="container text-center p-4 team">
  <h1 class="display-4">TEAM CARACOLE</h1>
</div>
<div class="d-flex justify-content-around text-center alig team">
  <div class="card p-2">
    <%= image_tag ("Jonathan-tongue.png") %>
      <p class="header">Jordan Creyelman</p>
      <p class="p-2 text-justify text-muted">Docteur Code au grand Coeur, sed eleifend libero mattis et. Vivamus vel arcu at nibh semper lobortis. Praesent et metus velit.</p>
      <a href="#" class="btn btn-light m-1"><span class="bouton">Portfolio</span></a>
      <a href="#" class="btn btn-light m-1"><span class="bouton">GitHub</span></a>
  </div>
  <div class="card p-2">
    <%= image_tag ("julien-dort.png") %>
      <p class="header">Kim Soly</p>
      <p class="p-2 text-justify text-muted">Ut lacinia pharetra elit, sed eleifend libero mattis et. Vivamus vel arcu at nibh semper lobortis. Praesent et metus velit.</p>
      <a href="#" class="btn btn-light m-1"><span class="bouton">Portfolio</span></a>
      <a href="#" class="btn btn-light m-1"><span class="bouton">GitHub</span></a>
  </div>
  <div class="card p-2">
    <%= image_tag ("steph-wink.png") %>
      <p class="header">Marie de la Jonquille</p>
      <p class="p-2 text-justify text-muted">Ut lacinia pharetra elit, sed eleifend libero mattis et. Vivamus vel arcu at nibh semper lobortis. Praesent et metus velit.</p>
      <a href="#" class="btn btn-light m-1"><span class="bouton">Portfolio</span></a>
      <a href="#" class="btn btn-light m-1"><span class="bouton">GitHub</span></a>
  </div>
  <div class="card p-2">
    <%= image_tag ("Houned-peace.png") %>
      <p class="header presentation">Adrien Kiried</p>
      <p class="p-2 text-justify text-muted">Ut lacinia pharetra elit, sed eleifend libero mattis et. Vivamus vel arcu at nibh semper lobortis. Praesent et metus velit.</p>
      <a href="#" class="btn btn-light m-1"><span class="bouton">Portfolio</span></a>
      <a href="#" class="btn btn-light m-1"><span class="bouton">GitHub</span></a>
  </div>
  <div class="card p-2">
    <%= image_tag ("Glen-smile.png") %>
      <p class="header">Louis Lionel</p>
      <p class="p-2 text-justify text-muted">Ut lacinia pharetra elit, sed eleifend libero mattis et. Vivamus vel arcu at nibh semper lobortis. Praesent et metus velit.</p>
      <a href="#" class="btn btn-light m-1"><span class="bouton">Portfolio</span></a>
      <a href="#" class="btn btn-light m-1"><span class="bouton">GitHub</span></a>
  </div>
  <div class="card p-2">
    <%= image_tag ("kim-knock.png") %>
      <p class="header">Juan Pecan</p>
      <p class="p-2 text-justify text-muted">Ut lacinia pharetra elit, sed eleifend libero mattis et. Vivamus vel arcu at nibh semper lobortis. Praesent et metus velit.</p>
      <a href="#" class="btn btn-light m-1"><span class="bouton">Portfolio</span></a>
      <a href="#" class="btn btn-light m-1"><span class="bouton">GitHub</span></a>
  </div>
</div>
  <div class="card p-2">
      <p class="header"></p>
      <p class="p-2 text-justify text-muted">Ut lacinia pharetra elit, sed eleifend libero mattis et. Vivamus vel arcu at nibh semper lobortis. Praesent et metus velit.</p>
      <a href="#" class="btn btn-light m-1"><span class="bouton">Portfolio</span></a>
      <a href="#" class="btn btn-light m-1"><span class="bouton">GitHub</span></a>
  </div>
</div>

app/views/pages/welcome.html.erb
<center><h1>Salut à toi <%= @name %> !</h1><br>
<h4><Ici mon projet de Gossip, tu pourras créer à ta convenance le potion que tu souhaites, tu veux : 
<br>
Parler du mon temps, écrire un article palpitant ou même parler de ta voisine ? 
<br>
<strong>Ici tout est possible !</strong>
<br>
Alors regales toi !</center></h4>

app/views/posts/edit.html.erb
<h1>Update post :</h1>

<%= form_with model: @post do |form| %>

    <div class="form-group">
    <label>Title :</label>
    <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
    <label>Content :</label>
    <%= form.text_area :content, class: "form-control" %>
    </div>

    <div class="form-group" style="padding-top: 1rem;">
    <button type="submit" class="btn btn-primary">Update</button>
    </div>
   
<% end %>
  

app/views/posts/index.html.erb
<h1>Posts :</h1>


<% @posts.each do |post| %>
    <h2><%= post.title %></h2>
    <p><%= post.content %></p>
    <p>
        <a href="<%= post_path(post.id) %>" class="btn btn-primary">Show more</a>
        <a href="<%= edit_post_path(post.id) %>" class="btn btn-secondary">Edit Piaf</a>
        <a href="<%= edit_post_path(post.id) %>" class="btn btn-info" data-confirm="Are U update?" data-method="UPDATE">Update</a>
        <a href="<%= post_path(post.id) %>" class="btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE">Delete</a>
        <button type="button" class="btn btn-warning">Add to Cart</button>
        <button type="button" class="btn btn-light">Add to List</button>
        
    </p>
<% end %>

<p>
    <a href="<%= new_post_path %>" class="btn btn-success">Post your gossip</a> 
</p>

app/views/posts/new.html.erb
<h1>New post </h1>

<%= debug @gossip %>

<%= form_with model: @post do |form| %>

    <div class="form-group">
    <label>Title :</label>
    <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
    <label>Content :</label>
    <%= form.text_area :content, class: "form-control" %>
    </div>

    <div class="form-group" style="padding-top: 1rem;">
    <button type="submit" class="btn btn-primary">New post</button>
    </div>
       
<% end %>



<%if @gossip != nil%>
   <% if @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
<%end%>

app/views/posts/show.html.erb
    <h1><%= @post.title %></h1>
    <p><%= @post.content %></p>
    <p><%= @post.author %>
    <p><%= @post.city %>

    <p>
        <a href="<%= posts_path %>" class="btn btn-primary">Back</a>
        <button type="button" class="btn btn-success">Say my name</button>
    </p>

app/views/users/edit.html.erb
<h1>Update user :</h1>

<%= form_with model: @user do |form| %>

    <div class="form-group">
    <label>Title :</label>
    <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
    <label>Content :</label>
    <%= form.text_area :content, class: "form-control" %>
    </div>

    <div class="form-group" style="padding-top: 1rem;">
    <button type="submit" class="btn btn-primary">Update</button>
    </div>

<% end %>

app/views/users/index.html.erb
<h1>users :</h1>


<% @users.each do |user| %>
    <h2><%= user.first_name %></h2>
    <p><%= user.email %></p>
    <p>
        <a href="<%= user_path(user.id) %>" class="btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE">Delete</a>
    </p>
<% end %>

<p>
    <a href="<%= new_user_path %>" class="btn btn-success">New user</a> 
</p>

app/views/users/new.html.erb
<h1>Create user :</h1>

<%= form_with model: @user do |form| %>

    <div class="form-group">
    <label>Name :</label>
    <%= form.text_field :first_name, class: "form-control" %>
    </div>

    <div class="form-group">
    <label>Email :</label>
    <%= form.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
    <label>Password :</label>
    <%= form.password_field :password_digest, class: "form-control" %>
    </div>

    <div class="form-group">
    <label>Confirm Password :</label>
    <%= form.password_field :password_digest, class: "form-control" %>
    </div>

    <div class="form-group" style="padding-top: 1rem;">
    <button type="submit" class="btn btn-primary">Create</button>
    </div>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.first_name %></h1>
<p><%= @user.last_name %></p>

<p>
    <a href="<%= users_path %>" class="btn btn-primary">Back</a>
</p>